SELECT 
    v."UserID",
    v."CHANNEL2" AS CHANNEL,

    -- Parse timestamp into different granularities
    TO_TIMESTAMP(v.CONVERTEDRECORDDATE2, 'YYYY/MM/DD HH24:MI') AS RECORD_TS,
    TO_DATE(TO_TIMESTAMP(v.CONVERTEDRECORDDATE2, 'YYYY/MM/DD HH24:MI')) AS RECORD_DATE,
    CAST(TO_TIMESTAMP(v.CONVERTEDRECORDDATE2, 'YYYY/MM/DD HH24:MI') AS TIME) AS RECORD_TIME,
    DAYNAME(TO_DATE(TO_TIMESTAMP(v.CONVERTEDRECORDDATE2, 'YYYY/MM/DD HH24:MI'))) AS DAY_OF_WEEK,

    -- Session metrics
    COUNT(*) AS TOTAL_SESSIONS,
    SUM(DATEDIFF('minute', TIME '00:00:00', v.DURATION2)) AS TOTAL_DURATION_MIN,
    AVG(DATEDIFF('minute', TIME '00:00:00', v.DURATION2)) AS AVG_DURATION_MIN,

    -- Duration buckets
    CASE  
        WHEN DATEDIFF('minute', TIME '00:00:00', v.DURATION2) < 5  THEN 'Very Short'
        WHEN DATEDIFF('minute', TIME '00:00:00', v.DURATION2) BETWEEN 5 AND 15  THEN 'Short'
        WHEN DATEDIFF('minute', TIME '00:00:00', v.DURATION2) BETWEEN 16 AND 30 THEN 'Medium'
        WHEN DATEDIFF('minute', TIME '00:00:00', v.DURATION2) BETWEEN 31 AND 60 THEN 'Long'
        ELSE 'Very Long'
    END AS DURATION_BUCKET,

    -- Age segmentation
    CASE
        WHEN p.AGE BETWEEN 1 AND 12 THEN 'Kids'
        WHEN p.AGE BETWEEN 13 AND 18 THEN 'Teens'
        WHEN p.AGE BETWEEN 19 AND 35 THEN 'Youth'
        WHEN p.AGE BETWEEN 36 AND 60 THEN 'Adults'
        ELSE 'Senior Citizen'
    END AS AGE_BUCKET,

    -- Demographics
    p.GENDER,
    p.RACE,
    p.PROVINCE

FROM BRIGHTTVDATABASE.BRIGHTTVSCHEMA.VIEWERSHIP v
LEFT JOIN BRIGHTTVDATABASE.BRIGHTTVSCHEMA.USERPROFILE p
       ON v."UserID" = p.USERID

GROUP BY 
    v."UserID",
    v."CHANNEL2",
    TO_TIMESTAMP(v.CONVERTEDRECORDDATE2, 'YYYY/MM/DD HH24:MI'),
    TO_DATE(TO_TIMESTAMP(v.CONVERTEDRECORDDATE2, 'YYYY/MM/DD HH24:MI')),
    CAST(TO_TIMESTAMP(v.CONVERTEDRECORDDATE2, 'YYYY/MM/DD HH24:MI') AS TIME),
    DAYNAME(TO_DATE(TO_TIMESTAMP(v.CONVERTEDRECORDDATE2, 'YYYY/MM/DD HH24:MI'))),
    
    CASE  
        WHEN DATEDIFF('minute', TIME '00:00:00', v.DURATION2) < 5  THEN 'Very Short'
        WHEN DATEDIFF('minute', TIME '00:00:00', v.DURATION2) BETWEEN 5 AND 15  THEN 'Short'
        WHEN DATEDIFF('minute', TIME '00:00:00', v.DURATION2) BETWEEN 16 AND 30 THEN 'Medium'
        WHEN DATEDIFF('minute', TIME '00:00:00', v.DURATION2) BETWEEN 31 AND 60 THEN 'Long'
        ELSE 'Very Long'
    END,
    
    CASE 
        WHEN p.AGE BETWEEN 1 AND 12 THEN 'Kids'
        WHEN p.AGE BETWEEN 13 AND 18 THEN 'Teens'
        WHEN p.AGE BETWEEN 19 AND 35 THEN 'Youth'
        WHEN p.AGE BETWEEN 36 AND 60 THEN 'Adults'
        ELSE 'Senior Citizen'
    END,
    
    p.GENDER,
    p.RACE,
    p.PROVINCE;
